const app = {
  stateStartButton: false,
  stateBurgerMenu: false,
  level_pushups: 'Easy',
  level_sitUps: 'Easy',
  level_squats: 'Easy',
  level_burpee: 'Easy',
  state_pushups: true,
  state_sitUps: true,
  state_squats: true,
  state_burpee: true,
  start_pushups: 0,
  start_sitUps: 0,
  start_squats: 0,
  start_burpee: 0,
  day_pushups: 0,
  day_sitUps: 0,
  day_squats: 0,
  day_burpee: 0,
  coefficient: 1,
  Easy: 1,
  Simply: 3,
  Average: 5,
  Hard: 8,
  Impossible: 10,
  sec: 0,
};

export default app;
