const language = {
  appLang: 'en',
  ru: ['Отжимания', 'Пресс', 'Приседания', 'Бёрпи', 'Невозможно', 'Жесткий', 'Средний', 'Просто', 'Легко',
    'января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря',
    'Брось себе вызов на 30 дней', 'Поехали', 'Тут появится упражнение', 'Ваш пол', 'мужской', 'женский', 'Ваш возраст', 'Вы делаете зарядку?', 'Никогда', 'По настроению', '1-2 раза в неделю', '3-4 раза в неделю', 'Каждый день', 'Сколько вы сделаете отжиманий за 60 секунд?', 'Сколько вы сделаете ситапов за 60 секунд?', 'Сколько вы сделаете приседаний за 60 секунд?', 'Тест пройден', 'Продолжить',
    'Статус: день', 'Статус: Просто сделай это!', 'Статус: Доступ закрыт', 'Потрачено !!!', 'Начать сначала',
    'Вы готовы пройти 30 дневный челлендж по', 'на уровне', 'Да', 'Нет', 'Пройти тест'],
  en: ['Pushups', 'SitUps', 'Squats', 'Burpees', 'Impossible', 'Hard', 'Average', 'Simply', 'Easy',
    'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December',
    'Challenge yourself for 30 days', ' Go ', ' An exercise will appear here ', ' Your gender ', ' Male ', ' Female ', ' Your age ', ' Are you doing exercises? ', ' Never ', ' By mood ', ' 1-2 times a week ', ' 3-4 times a week ', ' Every day ', ' How many push-ups will you do in 60 seconds? ', ' How many sit-ups will you do in 60 seconds? ', ' How many will you squat in 60 seconds? ', 'Test passed', 'Continue',
    'Status: day', 'Status: Just do it!', 'Status: Access denied', 'Spent !!!', 'Start over',
    'You are ready to complete the 30 day challenge for', 'at level', 'Yes', 'No', 'Take the test'],

  technique_ru_pushups_title: ['Как правильно делать отжимания от пола:'],
  technique_ru_pushups: ['Примите упор лежа (лягте лицом вниз на пол, руки поставьте чуть шире плеч). Придайте телу правильную позу для отжиманий от пола ‒ форму прямой линии. Плечи должны быть немного выше уровня таза. Голова должна смотреть в пол.Ладони — на вертикали плеч, параллельно друг другу, направление пальцев — параллельно телу. Правильная постановка рук при классических отжиманиях от пола — на ширине плеч или немного шире. Руки согнуты, локти направлены в стороны под углом 45 градусов от тела, пальцы рук смотрят вперед. Положение стоп непринципиально: они могут быть сведены либо расставлены. Плавно сгибайте локти медленно опускайтесь вниз, после чего поднимитесь обратно. Нижняя точка — по достижении прямого угла между бицепсом и предплечьем. Грудь касается пола. В верней позиции руки не распрямляют до конца, чтобы не блокировать локтевой сустав. В верхней точке задержаться. Чтобы повысить эффективность упражнения и не допустить травмоопасной осевой нагрузки на позвоночник, напрягите мышцы пресса.'],
  technique_en_pushups_title: ['How to do push-ups from the floor:'],
  technique_en_pushups: ['Take a lying position (lie face down on the floor, place your hands slightly wider than your shoulders). Give your body the correct push-up position - a straight line shape. The shoulders should be slightly above the level of the pelvis. The head should look at the floor. The palms are on the vertical of the shoulders, parallel to each other, the direction of the fingers is parallel to the body. The correct position of the hands for classic push-ups from the floor is shoulder-width apart or slightly wider. Arms bent, elbows pointing to the sides at an angle of 45 degrees from the body, fingers pointing forward. The position of the feet is not essential: they can be brought together or placed. Smoothly bend your elbows, slowly lower yourself down, and then rise back. The lowest point - upon reaching a right angle between the biceps and forearm. The chest touches the floor. In the correct position, the arms are not fully extended, so as not to block the elbow joint. Linger at the top point. To increase the effectiveness of the exercise and prevent traumatic axial loading on the spine, tighten the abdominal muscles.'],

  technique_ru_sitUps_title: ['Как правильно делать Ситапы:'],
  technique_ru_sitUps: ['1) Исходная позиция: атлет лежит на спине, ноги полусогнуты в коленях, руки выпрямлены и лежат над головой. Ягодицы, поясница и верх спины плотно прижаты к полу. Ступни ног плотно прижаты к полу. Если ступни будут отрываться во время подхода, попробуйте упираться в пол только пятками и распределяйте центр тяжести, как при приседаниях со штангой. 2) Атлет начинает движение корпусом вверх, одновременно с этим выдыхая. Наша задача – подняться за счет усилия мышц пресса, спину стараемся при этом не округлять, а пальцами рук стараемся дотянуться до ступней. В верхней точке корпус должен быть расположен примерно под прямым углом по отношению к полу. 3) После касания ступней плавно начинайте опускаться вниз на вдохе, делая движение достаточно быстро, но подконтрольно. Держите руки прямыми над головой и дотроньтесь ими до пола, после чего повторите все движение с самого начала.'],
  technique_en_sitUps_title: ['How to do SitUps correctly:'],
  technique_en_sitUps: ['1) Starting position: the athlete lies on his back, legs are bent at the knees, arms are straightened and lie over his head. The buttocks, lower back and upper back are firmly pressed to the floor. The feet are firmly pressed to the floor. If your feet come off during the approach, try to rest on the floor with your heels only and distribute the center of gravity as you would with a barbell squat. 2) The athlete begins to move the body upward, while exhaling at the same time. Our task is to rise due to the effort of the abdominal muscles, while trying not to round our back, and with our fingers we try to reach our feet. At the top, the body should be approximately at right angles to the floor. 3) After touching the feet, slowly begin to descend downward as you inhale, making the movement fast enough, but under control. Keep your arms straight above your head and touch them to the floor, then repeat the entire movement from the beginning.'],

  technique_ru_squats_title: ['Как правильно делать приседания:'],
  technique_ru_squats: ['1) Поставьте ноги на уровне ширины плеч. Расположите стопы так, чтобы носки были чуть развернуты в стороны. 2) Колени и носки стоп направляйте в одну сторону. Перенесите вес тела на пятки. 3) Стопы прижмите плотно к полу и не приподнимайте их на протяжении всего упражнения. 4) Если вы выполняете присед без дополнительного отягощения, руки можно держать перед собой (так проще всего держать равновесие), завести за голову или скрестить перед грудью. 5) Держите поясницу «лодочкой» с легким прогибом. Не округляйте ее, в том числе в грудном отделе. 6) Старайтесь не наклоняться вперед. Следите за осанкой. 7) Не сводите коленки внутрь и не разводите их в стороны, вставая из нижнего положения. Колени должны “смотреть” туда же, куда и стопы. Старайтесь также не выводить колени вперед за уровень носков. 8) Глубоко вдохните в начале упражнения. В дальнейшем при подъеме нужно выдыхать, при опускании – вдыхать. 9) Опускаться нужно как минимум до параллели бедра с полом. Лучше – еще глубже, хотя это зависит от цели упражнения. 10) Не нужно выпрямлять до конца ноги в верхней точке. Чуть-чуть не доходя до полного выпрямления сразу же начинайте движение вниз.'],
  technique_en_squats_title: ['How to do squats correctly:'],
  technique_en_squats: ['1) Place your feet shoulder-width apart. Position your feet so that the toes are slightly turned to the sides. 2) Point your knees and toes in the same direction. Shift your weight onto your heels. 3) Press your feet firmly to the floor and do not lift them throughout the exercise. 4) If you are doing a squat without additional weights, you can hold your arms in front of you (this is the easiest way to keep balance), put them behind your head or cross in front of your chest. 5) Keep your lower back in a boat with a slight bend. Do not round it, including in the chest. 6) Try not to lean forward. Watch your posture. 7) Do not bring your knees inward and do not spread them to the sides, rising from a lower position. The knees should "look" in the same direction as the feet. Also, try not to push your knees forward beyond the level of the socks. 8) Take a deep breath at the beginning of the exercise. In the future, when lifting, you need to exhale, when lowering, inhale. 9) You need to descend at least to the parallel of the thigh with the floor. Better - even deeper, although it depends on the purpose of the exercise. 10) You do not need to straighten your legs to the end at the top point. Just before reaching full extension, immediately start moving down. '],

  technique_ru_burpee_title: ['Как правильно делать бёрпи'],
  technique_ru_burpee: ['1) стойка прямо, ноги на ширине плеч; 2) глубокий присед до момента, когда сможете поставить ладони на пол; 3) перенос веса тела на руки и переход прыжком в упор лёжа; 4) отжимание; 5) возврат в присед через прыжок; 6) прыжок вверх с хлопком над головой.'],
  technique_en_burpee_title: ['How to do burpees correctly:'],
  technique_en_burpee: ['1) stand straight, feet shoulder-width apart; 2) deep squat until you can put your palms on the floor; 3) the transfer of body weight to the arms and the transition by jumping to the lying position; 4) push-ups; 5) return to squat through a jump; 6) jump up with a clap over your head.'],

  rules_ru_title: ['Правила участия'],
  rules_en_title: ['Rules of participation'],
  rules_ru: ['Приложение даёт возможность пройти челлендж длиной в 30 дней!', 'Есть 4 вида упражнений: отжимания, ситапы, приседания, бёрпи', 'Есть 5 уровней сложности челленджей: легко, просто, нормально, сложно, неовзможно.', 'По умолчанию стоит уровень Легко', 'Узнать свой уровень можно пройдя специальный тест. Примечание: если челлендж уже начат, то по этому упражнению уровень не поменяется', 'Переход на новый уровень происходит и после прохождения челленджа', 'Одновременно можно проходить только 1 челлендж', 'Пропускаешь 1 день в челлендже - челлендж проигран. Можно начать заново.'],
  rules_en: ['The application allow you to complete a 30-day challenge!', 'There are 4 types of exercises: push-ups, sit-ups, squats, burpees', 'There are 5 difficulty levels of challenges: easy, simple, normal, difficult, impossible.', 'The default is Easy', 'You can find out your level by passing a special test. Note: if the challenge has already started, then the level will not change for this exercise ', ' The transition to a new level occurs after passing the challenge ', ' You can only complete 1 challenge at a time ', ' If you miss 1 day in the challenge, the challenge is lost. You can start over. '],

  random_ru: ['10 отжиманий', '15 отжиманий', '10 приседаний', '15 приседаний', '10 ситапов', '15 ситапов', '10 бёрпи', '15 бёрпи', '10 выпадов', '15 выпадов', 'подъём ног 10 раз', 'подъём ног 15 раз', 'выпады в бок 10 раз', 'выпады в бок 15 раз', 'обратные отжимания 10 раз', 'обратные отжимания 15 раз'],
  random_en: ['10 push-ups', ' 15 push-ups', '10 squats', ' 15 squats', '10 sit-ups', ' 15 sit-ups', '10 burpees', ' 15 burpees', '10 lunges', ' 15 lunges', 'raising legs 10 times', ' raising legs 15 times', 'lunges to the side 10 times', ' lunges to the side 15 times', 'reverse push-ups 10 times', ' reverse push-ups 15 times'],

  random_ru_rules: ['Правила: Участвовать может как один так и несколько человек. После нажатия на кнопку "Поехали" на экране появится задание, которое необходимо выполнить за 60 сек. После того как первый участник выполнил свое задание, кнопка нажимается еще раз, и это задание выполняет следующий участник. Так испытание продолжается по кругу. Выигрывает тот, кто сможет выполнить своё задание, в то время как остальные уже сдались.'],
  random_en_rules: ['Rules: One or several people can participate. After clicking on the "Go" button, a task will appear on the screen, which must be completed in 60 seconds. After the first participant has completed his task, the button is pressed again, and this task is performed by the next participant. So the test continues in a circle. The winner is the one who can complete his task, while the others have already surrendered.'],

  random_ru_rules_title: ['Случайное упражнение'],
  random_en_rules_title: ['Random exercise'],

  test_ru_title: ['Фитнес-тест'],
  test_en_title: ['Fitness test'],

  test_ru: ['Ваш пол'],
  test_en: ['Your gender'],

  сhallenge_ru: ['Ваш челлендж по', 'начался', 'и закончится', 'Сегодня', 'день,', 'необходимо сделать', 'подходов по', 'раз(а)', 'После выполнения нажмите на кнопку:', 'Готово!', 'Сделай это!!!', 'На сегодня ты выполнил задание', 'Техника выполнения', 'Ты выполнил челлендж, теперь повышается твой уровень по этому упражнению!'],
  сhallenge_en: ['Your challenge by', 'started', 'and will end', 'Today', 'day,', 'must be done', 'approaches by', 'time (s)', 'After completion, press the button : ', ' Done! ', ' Do this!!! ', ' For today you have completed the task ', ' Technique of execution ', ' You have completed the challenge, now your level for this exercise is increasing! '],

  menu_ru: ['Домашняя страница', 'Фитнес-тест', 'Правила участия', 'Рандом-упражнения'],
  menu_en: ['Home page', 'Fitness test', 'Participation rules', 'Random exercises'],
};

export default language;
